# Generated by Django 3.0.4 on 2020-04-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200401_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='inicjator',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='wypociny',
        ),
    ]
