# Generated by Django 3.0.4 on 2020-04-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200401_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='inicjator',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='wypociny',
            new_name='text',
        ),
    ]
